name = "backend"
main = "src/index.ts"
compatibility_date = "2023-03-04"

[[ d1_databases ]]
database_id = "9364baf2-f635-4baa-9f85-b13ab7e534ef"
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "watch-on-floatplane"
